[package]
name = "eyre-test"
version = "0.1.0"
authors = ["Michael Chen <mikatpt@gmail.com>"]
edition = "2021"

[lib]
crate_type = ["proc-macro"]

[dependencies]
quote = "1.0.10"
syn = { version = "1.0.57", features = ["full"] }
